[package]
name = "spin-practice"
authors = ["Jinwoo Kim <jinwookim@kw.ac.kr>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"
wit-bindgen-rt = { version = "0.25.0", features = ["bitflags"] }

[workspace]
