spin_manifest_version = 2

[application]
name = "cc-spin-test"
version = "0.1.0"
authors = ["Jinwoo Kim <jinwookim@kw.ac.kr>"]
description = ""

[[trigger.http]]
route = "/..."
component = "cc-spin-test"

[component.cc-spin-test]
source = "target/wasm32-wasi/release/cc_spin_test.wasm"
allowed_outbound_hosts = ["*://*:*"]

[component.cc-spin-test.build]
command = "cargo component build --release"
watch = ["src/**/*.rs", "Cargo.toml"]
